---
title: "Benton Park"
author: "dblodgett.h2o@gmail.com"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=6,
  fig.height=4)

oldoption <-
  options(scipen = 9999,
          "rgdal_show_exportToProj4_warnings"="none")

library(gpxr)
library(dplyr)
library(sf)
library(mapview)
mapviewOptions(fgb = FALSE)
```

```{r} 

f <- "../gpx/RGT_Benton_Park_Classic_(copy).gpx"

track <- load_track_points(f)

track <- sf::st_transform(track, 5070)

track <- simplify_track(track, 0)

plot(st_geometry(track))

# from manual map selection
control_geo <- read_sf("../gpx/RGT_Benton_Park_Classic_(copy)_control.gpkg")
control_geo <- output_control_point

control_geo <- sf::st_transform(control_geo, 5070)

control <- list(start_ids = control_geo$start_id, end_ids = control_geo$end_id,
                points = lapply(1:nrow(control_geo), 
                                function(x, p) as.numeric(p[x, ]), 
                                p = st_coordinates(control_geo)))

for(i in 1:length(control$points)) {
  track <- gpxr:::bez_smooth(track, control$start_ids[i], control$end_ids[i], 
                             control$points[[i]])
}

track$track_seg_point_id <- 1:nrow(track)

mapview(list(track, control_geo))
```

```{r}
domains <- c(0, 47, 67, 125, 150, nrow(track))
smoothers <- c(4,  4,  4,  5,   5)

track2 <- smooth_elev(track, domains, smoothers)

plot(track$track_seg_point_id, track$ele)
points(track2$track_seg_point_id, track2$ele, col = "red", pch = ".", cex = 3)
abline(v = domains)
```

```{r}
track <- mutate(track, ele = track2$ele, track_seg_id = 0, track_fid = 0, time = "")

track <- sf::st_transform(track, 4326)

unlink("../gpx/Benton_Park.gpx")

write_sf(track, "../gpx/Benton_Park.gpx", "track_points", driver = "GPX")
```

```{r teardown, include=FALSE}
options(oldoption)
```
