---
title: "JMSR"
author: "dblodgett.h2o@gmail.com"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=6,
  fig.height=4)

oldoption <-
  options(scipen = 9999,
          "rgdal_show_exportToProj4_warnings"="none")

library(gpxr)
library(dplyr)
library(sf)
library(mapview)
mapviewOptions(fgb = FALSE)
```

```{r} 

f <- "../gpx/JMSR_curves.gpx"

track <- load_track_points(f)

track <- sf::st_transform(track, 5070)

track <- simplify_track(track, .01)

plot(st_geometry(track))

mapview(track)
```

```{r}
track2 <- clean_elev(track, window = 5)

plot(track$track_seg_point_id, track$ele)
points(track2$track_seg_point_id, track2$ele, col = "red", pch = ".", cex = 3)
```

```{r}
track <- mutate(track, ele = track2$ele, track_seg_id = 0, track_fid = 0, time = "")

track_dist <- gpxr::add_distance(track)

track <- track[!abs(track_dist$slope) > 0.1, ]

track <- sf::st_transform(track, 4326)

unlink("../gpx/JMSR_crit.gpx")

write_sf(track, "../gpx/JMSR_crit.gpx", "track_points", driver = "GPX")
```

```{r teardown, include=FALSE}
options(oldoption)
```
